### ISSUE TITLE
error open inventory!

### ISSUE THREAD

**Issue by florinprc** [Reload-X/qb-inventory#10]
I installed the fresh inventory, I didn't change anything, I still went to qb-inventory, when I want to open the inventory, I get an error from here for k, v in pairs(QBCore.Shared.Items) do
            if type(v) == "table" and v.type == "weapon" then
                table.insert(filterWeapon, v.label)
            end
        end
but I modified it to be able to use it

**Comment by Reload-X** [comment]
to use what it works default

**Comment by florinprc** [comment]
no is not work default,check again!

**Comment by Reload-X** [comment]
your the only person reporting this issue so

**Comment by Reload-X** [comment]
and atleast 50 people use it

**Comment by florinprc** [comment]
Bro i told you is not work default for me,i make something edit to work for
me becouse i can not open inventory,give me yours discord and il show you
