### ISSUE TITLE
Congratulations on the excellent work, I have a simple question

### ISSUE THREAD

**Issue by didevlab** [Reload-X/qb-inventory#12]
Is there a possibility to enable the slots that are on the side of the body? Do these slots exist?
If they don't exist, can they be inserted?
Here's an example:
Once again, thank you very much for the great work

![image](https://github.com/Reload-X/qb-inventory/assets/69443153/13f88a35-3070-4186-aa9c-38632416abb3)

**Comment by Reload-X** [comment]
it was done before this release but its very poor and slots wasnt  corrected so i have attempted it yet
