### ISSUE TITLE
I can't open a glovebox or a shop.

### ISSUE THREAD

**Issue by Synex0001** [Reload-X/qb-inventory#14]
Shop error:
[     script:qb-shops] SCRIPT ERROR: @qb-shops/server/main.lua:166: No such export CreateShop in resource qb-inventory

Glovebox error:
[ script:qb-inventory] SCRIPT ERROR: @qb-inventory/server/main.lua:746: qb-inventory was unable to execute a query!
[ script:qb-inventory] Query: SELECT items FROM gloveboxitems WHERE plate = ?
[ script:qb-inventory] ["64ICX722"]
[ script:qb-inventory] Table 'qbcoreframework_7c809e.gloveboxitems' doesn't exist
[ script:qb-inventory] > GetOwnedVehicleGloveboxItems (@qb-inventory/server/main.lua:746)
[ script:qb-inventory] > handler (@qb-inventory/server/main.lua:1401)
[ script:qb-inventory] > logError (@oxmysql/dist/build.js:24889)
[ script:qb-inventory] > rawQuery (@oxmysql/dist/build.js:25056)
[ script:qb-inventory] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by Reload-X** [comment]
this is new qbcore exports my inventory doesnt support

**Comment by Synex0001** [comment]
Can you make your inventory script support the newest qbcore exports, please?

**Comment by Synex0001** [comment]
How can I downgrade my qbcore exports and which do I downgrade to for this inventory script to work?

**Comment by Synex0001** [comment]
Which qbcore exports version does your inventory script support?

**Comment by Reload-X** [comment]
Anything before “inventory update”

**Comment by Synex0001** [comment]
Sorry for asking but what can I do to downgrade it to make your inventory script work?

**Comment by Synex0001** [comment]
Just curious, but since Project Sloth modified their inventory script to operate with the "inventory update," would you be fixing your script as well now that Project Sloth has fixed their script so it works with the "inventory update"?

**Comment by kosar-omed** [comment]
Cloud do with updating to the newest QB Core. Shop functionality is really essential
