### ISSUE TITLE
qbcore install

### ISSUE THREAD

**Issue by promiiss033** [Reload-X/qb-inventory#17]
so iam kind of stuck at this first part, 

If you are using qb-core, you need to change e.g-inventory export names to qb-inventory. Otherwise it will not work properly
Update the exports below in the corresponding files and any other script you may have which use qb-inventory export

qb-core > client > functions.lua
qb-core > server > functions.lua
qb-core > server > player.lua

but if you are using qb its allready stock export qb-inventory,

but mine is not working

**Comment by promiiss033** [comment]
so what do i need toch change, do you have a example?

**Comment by DannyHD001** [comment]
> so what do i need toch change, do you have a example?

if using qb-inventory from before there is no need for any changes here. But you can check those files to make sure they use qb-inventory and not something else.
