### ISSUE TITLE
ScreenSize issue

### ISSUE THREAD

**Issue by DannyHD001** [Reload-X/qb-inventory#18]
Hi
Just noticed that having a large screen is causing some issues with wounding labels :-)

![image](https://github.com/Reload-X/qb-inventory/assets/34337548/beb15d31-4f0f-423d-a46a-98ee9b61d524)

**Comment by Reload-X** [comment]
support 1920 x 1080 only otherwise enable force UI

**Comment by promiiss033** [comment]
Got the same for 3440x1440, how to force UI?

**Comment by promiiss033** [comment]
Could you make it responsive ui? I think there are a lot of people these days with 4k screens

**Comment by Reload-X** [comment]
It was designed for 1920 x 1080 as that is the default resolution and is meant to be the only support resolution on fivem

**Comment by promiiss033** [comment]
Oke, and how do i enable force UI

**Comment by Reload-X** [comment]
fivem settings
