### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fuse9** [Reload-X/qb-inventory#2]
![image](https://github.com/Reload-X/qb-inventory/assets/32308171/6f189ffb-219e-4571-b6b0-97731f13e940)

any fix for this yet ? inventory is unusable as it is

**Comment by Reload-X** [comment]
No one else has this issue as far as i know

**Comment by fuse9** [comment]
There are others in PS discord with same issue. I am thinking it's something with new qbcore still looking into this

**Comment by Alexxxunchained** [comment]
Do not update to new qbcore, roll back to old version or u will get tons of error.

**Comment by fuse9** [comment]
I only get errors with this inventory I am staying updated I will get this working

**Comment by Alexxxunchained** [comment]
Mate if u made any progess plz let me know, Im still trapped in the update...

**Comment by Reload-X** [comment]
Doesnt work on new qbcore
