### ISSUE TITLE
An error occurred while calling export `OpenInventory` in resource `qb-inventory`:

### ISSUE THREAD

**Issue by xChristianTWM** [Reload-X/qb-inventory#20]
Hi, I use new qbcore, and when I try to open the stashes it shows me the following error. I am very new to this and I don't understand about lua. Could you update the script for new qbcore or tell me which lines of code I should modify and with what to solve this error? Thank you very much! Aesthetically the inventory is beautiful!
![imagen_2024-07-08_003127312](https://github.com/Reload-X/qb-inventory/assets/108093913/ea714bb0-95f6-44f2-aa9e-e8dad9d1698c)

**Comment by promiiss033** [comment]
Use new-qb-inventory
