### ISSUE TITLE
Stash

### ISSUE THREAD

**Issue by Rippan88** [Reload-X/qb-inventory#24]
Items put in stashes is not removed from stashes when i take it out, i can duplicate the items this way. and i dont know how to fix

**Comment by KaiserFahim** [comment]
@Rippan88  Any Video? I also wanna check it from my side. If Yes, I will tell Reload also to fix this.

**Comment by Rippan88** [comment]
Hi i don’t have video of it but I think I know what’s the problem . I was running ox_inventory before and tried to go over to ps inventory and couldn’t take away ox_inventory since it changes a lot of the basic script codings . I’m now reloading all basic script back in without ox inventory Skickat från min iPhone24 juli 2024 kl. 21:51 skrev Kaiser Fahim ***@***.***>:﻿
@Rippan88  Any Video? I also wanna check it from my side. If Yes, I will tell Reload also to fix this.
