### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by JordanBScott** [Reload-X/qb-inventory#3]
Getting this error when trying to open my inventory... Just installed it

`[ script:qb-inventory] SCRIPT ERROR: @qb-inventory/server/main.lua:2445: attempt to sub a 'number' with a 'string'

[ script:qb-inventory] > TriggerCallback (@qb-core/server/functions.lua:456)

[ script:qb-inventory] > handler (@qb-core/server/events.lua:105)

[      script:qb-core] SCRIPT ERROR: error object is not a string`

**Comment by hamatahavet** [comment]
i got the same error on a big screen i think that's the problem

**Comment by Reload-X** [comment]
Doesnt work on new qbcore
