### ISSUE TITLE
duplicated info, error in app.js line 643

### ISSUE THREAD

**Issue by SmithyDevelopment** [Reload-X/qb-inventory#6]
mechboard entered twice, harness not entered at all.. 

case "harness":
                 if (itemData.name == "mechboard") {
                $(".item-info-title").html("<p>" + itemData.label + "</p>");
                $(".item-info-description").html(
                    "<p>" + itemData.info.vehplate + "</p>" +
                    "<p>" + itemData.info.veh + "</p>"
                )
                }
                else if (itemData.name == "mechboard") {
                    $(".item-info-title").html("<p>" + itemData.label + "</p>");
                    $(".item-info-description").html(
                        "<p>" + itemData.info.vehplate + "</p>" +
                        "<p>" + itemData.info.veh + "</p>"
                )}

**Comment by Reload-X** [comment]
Fixed
