### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HunterB72** [Reload-X/qb-inventory#8]
Hello, not too sure if I am maybe doing something wrong but I keep getting this error.

[ script:qb-inventory] SCRIPT ERROR: @qb-inventory/server/main.lua:2445: attempt to sub a 'number' with a 'string'
[ script:qb-inventory] > TriggerCallback (@qb-core/server/functions.lua:456)
[ script:qb-inventory] > handler (@qb-core/server/events.lua:105)
[      script:qb-core] SCRIPT ERROR: error object is not a string

**Comment by Reload-X** [comment]
If you are using the new qb it doesnt not work this Inventory only works before march nothing after

**Comment by HunterB72** [comment]
well that explains it thank you very much
